# File: .github/workflows/repo-sync.yml
name: sync-huanghyw/jd_seckill
on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [master]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/huanghyw/jd_seckill.git"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
